// This is a comprehensive list of vocabulary words for 3rd, 4th, and 5th-grade levels.
// It includes words aligned with the Arizona 5th Grade ELA standards, such as academic,
// science, and civics vocabulary. The list is alphabetized and de-duplicated.
const spellingWords = [
    { word: "absorb", definition: "To soak up or take in." },
    { word: "accommodate", definition: "To provide lodging or sufficient space for." },
    { word: "adventure", definition: "An unusual and exciting experience." },
    { word: "amendment", definition: "A change or addition to a legal document or law, like the Constitution." },
    { word: "analyze", definition: "To examine something in detail to understand its parts." },
    { word: "ancient", definition: "Belonging to the very distant past and no longer in existence." },
    { word: "annual", definition: "Occurring once every year." },
    { word: "anxious", definition: "Experiencing worry, unease, or nervousness." },
    { word: "apparent", definition: "Clearly visible or understood; obvious." },
    { word: "argument", definition: "An exchange of opposite views, often heated." },
    { word: "atmosphere", definition: "The gasses surrounding the Earth or another planet." },
    { word: "baffled", definition: "Totally confused or perplexed." },
    { word: "beautiful", definition: "Pleasing the senses or mind aesthetically." },
    { word: "behind", definition: "At or to the far side of something." },
    { word: "believe", definition: "To accept something as true; feel sure of the truth of." },
    { word: "bizarre", definition: "Very strange or unusual, especially so as to cause interest or amusement." },
    { word: "boycott", definition: "To refuse to buy or handle goods as a protest." },
    { word: "brief", definition: "Lasting for only a short time." },
    { word: "cautious", definition: "Careful to avoid potential problems or dangers." },
    { word: "challenge", definition: "A call to take part in a contest or competition." },
    { word: "chronological", definition: "Starting with the earliest and following the order in which they occurred." },
    { word: "colleague", definition: "A person with whom one works in a profession or business." },
    { word: "committee", definition: "A group of people appointed for a specific function." },
    { word: "community", definition: "A group of people living in the same place or having a characteristic in common." },
    { word: "compare", definition: "To note the similarities between things." },
    { word: "consequence", definition: "A result or effect of an action or condition." },
    { word: "constitution", definition: "The set of fundamental principles by which a state or country is governed." },
    { word: "contrast", definition: "To note the differences between things." },
    { word: "contribute", definition: "To give in order to help achieve or provide something." },
    { word: "courageous", definition: "Not deterred by danger or pain; brave." },
    { word: "curiosity", definition: "A strong desire to know or learn something." },
    { word: "curious", definition: "Eager to know or learn something." },
    { word: "data", definition: "Facts and statistics collected for reference or analysis." },
    { word: "deceive", definition: "To cause someone to believe something that is not true." },
    { word: "definitely", definition: "Without doubt; clearly." },
    { word: "delicious", definition: "Highly pleasant to the taste." },
    { word: "democracy", definition: "A system of government by the whole population, typically through elected representatives." },
    { word: "describe", definition: "To give a detailed account in words." },
    { word: "dialogue", definition: "A conversation between two or more people in a book, play, or movie." },
    { word: "disappoint", definition: "To fail to fulfill the hopes or expectations of." },
    { word: "disaster", definition: "A sudden event that causes great damage or loss of life." },
    { word: "discover", definition: "To find something unexpectedly or during a search." },
    { word: "doubt", definition: "A feeling of uncertainty or lack of conviction." },
    { word: "ecosystem", definition: "A community of living organisms interacting with their physical environment." },
    { word: "efficient", definition: "Achieving maximum productivity with minimum wasted effort." },
    { word: "enormous", definition: "Very large in size, quantity, or extent." },
    { word: "environment", definition: "The surroundings or conditions in which a person, animal, or plant lives." },
    { word: "essential", definition: "Absolutely necessary; extremely important." },
    { word: "evidence", definition: "Facts or information that show something is true or valid." },
    { word: "exaggerate", definition: "To represent something as being larger or worse than it really is." },
    { word: "exhaust", definition: "To make someone feel very tired." },
    { word: "explain", definition: "To make an idea or situation clear to someone by describing it in more detail." },
    { word: "explore", definition: "To travel through an unfamiliar area in order to learn about it." },
    { word: "extraordinary", definition: "Very unusual or remarkable." },
    { word: "familiar", definition: "Well known from long or close association." },
    { word: "famous", definition: "Known about by many people." },
    { word: "figurative language", definition: "Language that uses words with a meaning that is different from the literal interpretation." },
    { word: "frequently", definition: "Often; on many occasions." },
    { word: "friendly", definition: "Kind and pleasant." },
    { word: "frustrated", definition: "Feeling or expressing distress and annoyance." },
    { word: "generous", definition: "Showing a readiness to give more of something than is necessary or expected." },
    { word: "gigantic", definition: "Of very great size or extent; huge or enormous." },
    { word: "government", definition: "The governing body of a nation, state, or community." },
    { word: "guarantee", definition: "A formal promise that certain conditions will be fulfilled." },
    { word: "harass", definition: "To subject to aggressive pressure or intimidation." },
    { word: "hesitate", definition: "To pause before saying or doing something, especially through uncertainty." },
    { word: "humorous", definition: "Causing laughter and amusement; comic." },
    { word: "hypothesis", definition: "A proposed explanation made on limited evidence for further investigation." },
    { word: "idiom", definition: "A common expression with a meaning different from the literal meaning of its words (e.g., 'it's raining cats and dogs')." },
    { word: "illustrate", definition: "To explain or make something clear by using examples, charts, or pictures." },
    { word: "imagine", definition: "To form a mental image or concept of." },
    { word: "immediately", definition: "At once; instantly." },
    { word: "important", definition: "Of great significance or value." },
    { word: "increase", definition: "To become or make greater in size, amount, or degree." },
    { word: "inference", definition: "A conclusion reached on the basis of evidence and reasoning." },
    { word: "inspect", definition: "To look at someone or something closely to check for flaws." },
    { word: "integrity", definition: "The quality of being honest and having strong moral principles." },
    { word: "interrupt", definition: "To stop the continuous progress of an activity or process." },
    { word: "island", definition: "A piece of land completely surrounded by water." },
    { word: "journey", definition: "An act of traveling from one place to another." },
    { word: "legislature", definition: "The group of people in a government that has the power to make or change laws." },
    { word: "leisure", definition: "Free time used for enjoyment." },
    { word: "listen", definition: "To give one's attention to a sound." },
    { word: "loyal", definition: "Giving or showing firm and constant support to a person or institution." },
    { word: "maneuver", definition: "A movement or series of moves requiring skill and care." },
    { word: "meadow", definition: "A piece of grassland, especially one used for hay." },
    { word: "metaphor", definition: "A figure of speech where a word is applied to something to which it is not literally applicable." },
    { word: "mischievous", definition: "Causing or showing a fondness for causing trouble in a playful way." },
    { word: "mystery", definition: "Something that is difficult or impossible to understand or explain." },
    { word: "necessary", definition: "Required to be done, achieved, or present; essential." },
    { word: "negotiate", definition: "To try to reach an agreement or compromise by discussion." },
    { word: "notice", definition: "The fact of observing or paying attention to something." },
    { word: "obstacle", definition: "A thing that blocks one's way or prevents progress." },
    { word: "occasion", definition: "A particular time or instance of an event." },
    { word: "observe", definition: "To notice or perceive something and register it as being significant." },
    { word: "opinion", definition: "A view or judgment formed about something, not necessarily based on fact." },
    { word: "perfect", definition: "Having all the required or desirable elements, qualities, or characteristics." },
    { word: "personification", definition: "Giving human qualities or abilities to an object or animal." },
    { word: "persuade", definition: "To cause someone to do something through reasoning or argument." },
    { word: "photosynthesis", definition: "The process plants use to convert light into energy." },
    { word: "popular", definition: "Liked, admired, or enjoyed by many people." },
    { word: "predict", definition: "To say or estimate that a specified thing will happen in the future." },
    { word: "prefix", definition: "A group of letters placed at the beginning of a word to change its meaning." },
    { word: "prejudice", definition: "An opinion that is not based on reason or actual experience." },
    { word: "privilege", definition: "A special right or advantage available only to a particular person or group." },
    { word: "promise", definition: "A declaration that one will do a particular thing." },
    { word: "protagonist", definition: "The leading character in a story." },
    { word: "rare", definition: "Not occurring very often." },
    { word: "recommend", definition: "To suggest something as being good or suitable for a purpose." },
    { word: "reluctant", definition: "Unwilling and hesitant; disinclined." },
    { word: "rescue", definition: "To save someone from a dangerous or distressing situation." },
    { word: "restaurant", definition: "A place where people pay to eat meals." },
    { word: "review", definition: "To examine or assess something formally with the possibility of instituting change." },
    { word: "rhythm", definition: "A strong, regular repeated pattern of movement or sound." },
    { word: "root word", definition: "The most basic part of a word that gives it its meaning." },
    { word: "secret", definition: "Something that is kept or meant to be kept unknown or unseen by others." },
    { word: "sensible", definition: "Done or chosen in accordance with wisdom or prudence; likely to be of benefit." },
    { word: "separate", definition: "To cause to move or be apart." },
    { word: "simile", definition: "A comparison of two different things using the words 'like' or 'as'." },
    { word: "sincerely", definition: "In a genuine way; from the heart." },
    { word: "special", definition: "Better, greater, or otherwise different from what is usual." },
    { word: "suffix", definition: "A group of letters placed at the end of a word to change its meaning." },
    { word: "summarize", definition: "To give a brief statement of the main points." },
    { word: "surprise", definition: "An unexpected or astonishing event, fact, or thing." },
    { word: "symbol", definition: "A thing that represents or stands for something else." },
    { word: "temperature", definition: "The degree of heat present in a substance or object." },
    { word: "thorough", definition: "Complete with regard to every detail." },
    { word: "tradition", definition: "The transmission of customs or beliefs from generation to generation." },
    { word: "travel", definition: "To make a journey, typically of some length." },
    { word: "unique", definition: "Being the only one of its kind; unlike anything else." },
    { word: "usual", definition: "Habitually or typically occurring or done." },
    { word: "variable", definition: "A factor or element that can change in an experiment or situation." },
    { word: "vehicle", definition: "A thing used for transporting people or goods." },
    { word: "wonder", definition: "A feeling of surprise mingled with admiration, caused by something beautiful or unfamiliar." },
];

